---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-vpe-gateway
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 0cb4c87d-e374-4113-9e69-c1deb00a17c5
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-vpc.sh"
        post_validation: "tests/scripts/post-validation-destroy-vpc.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
